version: "3"
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapi
      MYSQL_USER: webapi
      MYSQL_PASSWORD: webapi
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data:
